### DISCUSSION TITLE
how to improve performance?

### DISCUSSION THREAD

**Discussion by TITC** [lukas-blecher/LaTeX-OCR#146] [General]
This discussion is more close to an endless answer's question.

## Recap

Here is some related information I have found, contains two issues https://github.com/lukas-blecher/LaTeX-OCR/issues/27#issue-948197787, https://github.com/lukas-blecher/LaTeX-OCR/issues/44#issue-1033177422 about BLEU and one [discussion](https://github.com/lukas-blecher/LaTeX-OCR/discussions/11) about LR schedule and optimizer.

## Experiment
I have added 0.35 million Wikipedia data to the training set, so there are 0.5 million in total. After that, I create a wandb sweep.

### panel1  [date&bleu](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-64--VmlldzoxOTQ5NDg1?accessToken=w50bbctb4b4h2b5jw7nsd1jvaf9vb6un411nkwcgoel4uaqw80ngw61vlasy6bfa)
![image](https://user-images.githubusercontent.com/35098797/166858235-eaeedac2-1cf8-440e-9fc1-3cf468ca194b.png)

### panel2 [hyperparamer influence](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-27--VmlldzoxOTQ5NTMw?accessToken=u3q53jmfsv9qzlg5pgio2vy7kb1o5se10d01lnk1b1xflob3l2f47ef6566qd9g2)
![image](https://user-images.githubusercontent.com/35098797/166858368-819a1911-f147-4692-bc99-cbcae73c8080.png)

### panel3 [fully connected layer style](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-48--VmlldzoxOTQ5NTY4?accessToken=rdfqemmescoqj6qtekg70v5gb4sxc6spoz8kkgi2t5iw77qlr081389yxsf4gy1i)

![image](https://user-images.githubusercontent.com/35098797/166859576-599150c9-77c6-4ca9-a823-62c3d7fb2014.png)

### panel4 [token acc](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-53--VmlldzoxOTQ5NTgx?accessToken=79pnx3e3o2epunjo15rnq29akd0v0iogtukkgs95e95ph0jaopy36oa287t2w636)

![image](https://user-images.githubusercontent.com/35098797/166859947-7ba17e16-766f-4628-90bf-48df8b82c37c.png)

### panel5 [val_bleu](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-30--VmlldzoxOTQ5NTg1?accessToken=97k8p6d335yoyjk4b6bjz73fu9nl6oveh6m01v6mma5ew3t5a5cprmxgledcdub7)

![image](https://user-images.githubusercontent.com/35098797/166860111-cfe12258-202f-4a52-aa59-4bf4f27173a3.png)

---
I have added more data and tried different hyperparameters which include lr schedule and optimizer, even the number of encoder layers and decoder layers, see panel3 [fully connected layer style](https://wandb.ai/yht4work/LaTeX-OCR-pix2tex/reports/Shared-panel-22-05-05-11-05-48--VmlldzoxOTQ5NTY4?accessToken=rdfqemmescoqj6qtekg70v5gb4sxc6spoz8kkgi2t5iw77qlr081389yxsf4gy1i) for more detail. But nothing gets better. What can I do to achieve higher performance? 

 5 days before, I reckon more data and hyper-parameter searching will work, but now the result is frustrating.

**Comment by lukas-blecher** [comment]
One thing I noticed that I don't know what it means is the `batchsize` parameter in the `fully` connected diagram. The values reported are not realistic. What is the meaning of that? Also, the batch size shouldn't have such an impact on the performance of the model.

I don't believe that the optimizer should be one of the first things to swap out. I could be wrong but the sentiment in ML seems to be that Adam or AdamW are the way to go. Also `min/max_height/width` shouldn't be parameters to change in the sweep because that means every model trains on a different dataset. Similarly, the `temperature` should be equal for all runs of the sweep so that the evaluation metrics can be compared with each other.

Instead you could play around with the `backbone_layers` in number of layers and depth.

I also don't understand the range of `gamma`. I'm using it for the StepLR scheduler and there it is used as a multiplicative for the lr (not sure what happens in your code for other schedulers), hence the value should be <1 if you want the LR to decrease. 

The metrics have a high variance, what value for `valbatches` did you use? Could also be connected to the `temperature` field as well.

Lastly, you can try to train for more iterations for the best hyper parameters. I've trained one model for 300k steps and it still improved somewhat in the last half.

**Reply by TITC** [reply]
Wow, a lot of problems of mine exposed to sunshine.

---
1. batch size 
```yaml
  batchsize:
    distribution: q_log_uniform
    max: 50
    min: 5
    q: 8
```
about [q_log_uniform](https://docs.wandb.ai/guides/sweeps/configuration), the official doc described as below
> Quantized log uniform. Returns round(X / q) * q where X is log_uniform. q defaults to 1.

2. sole variable
The reason I'm haven't control variates each time is that I think wandb `bayes` search strategy will config this automatically. The sweep code has nothing different with [train.py](https://github.com/lukas-blecher/LaTeX-OCR/blob/main/pix2tex/train.py) except removing argparse.
```python
    parser = argparse.ArgumentParser(description='Train model')
    parser.add_argument('--config', default=None,
                        help='path to yaml config file', type=str)
    parser.add_argument('--no_cuda', action='store_true', help='Use CPU')
    parser.add_argument('--debug', action='store_true', help='DEBUG')
    parser.add_argument(
        '--resume', help='path to checkpoint folder', action='store_true')
    parsed_args = parser.parse_args()
    if parsed_args.config is None:
        with in_model_path():
            parsed_args.config = os.path.realpath('settings/debug.yaml')
    with open(parsed_args.config, 'r') as f:
        params = yaml.load(f, Loader=yaml.FullLoader)
    args = parse_args(Munch(params), **vars(parsed_args))
    logging.getLogger().setLevel(logging.DEBUG if parsed_args.debug else logging.WARNING)
    seed_everything(args.seed)
    if args.wandb:
        if not parsed_args.resume:
            args.id = wandb.util.generate_id()
        wandb.init(config=dict(args), resume='allow',
                   name=args.name, id=args.id)
    train(args)
```
after
```python
    kwargs = {}
    kwargs["device"] = "cuda"
    kwargs["debug"] = False
    kwargs["resume"] = False
    kwargs["no_cuda"] = False
    kwargs["config"] = "model/settings/config.yaml"
    with open(kwargs["config"], 'r') as f:
        params = yaml.load(f, Loader=yaml.FullLoader)
    args = parse_args(Munch(params), **kwargs)
    wandb.init(config=dict(args), name=args.name)
    train(args)
```


3. backbone_layers

I will have a try and could you give some suggestions about a reasonable variable range?

4. gamma
I just create the sweep followed by [this tutorial](https://github.com/wandb/examples/tree/master/examples/pytorch/pytorch-cnn-fashion). There a lot of variables I do not actually know what's meaning, just create it and run. After your careful explanation, I get more clear about that part. Thanks for you explanation.

5. valbatches is the default 100 same with [config.yaml](https://github.com/lukas-blecher/LaTeX-OCR/blob/main/pix2tex/model/settings/config.yaml#L51)
6. sweep.config
```yaml
method: bayes
metric:
  goal: maximize
  name: val/bleu
parameters:
  batchsize:
    distribution: q_log_uniform
    max: 50
    min: 5
    q: 8
  dim:
    distribution: int_uniform
    max: 512
    min: 128
  encoder_depth:
    distribution: int_uniform
    max: 16
    min: 2
  gamma:
    distribution: uniform
    max: 1.999
    min: 0.49975
  heads:
    distribution: int_uniform
    max: 16
    min: 4
  lr:
    distribution: uniform
    max: 0.002
    min: 0.0005
  lr_step:
    distribution: int_uniform
    max: 60
    min: 15
  max_height:
    distribution: int_uniform
    max: 384
    min: 96
  max_seq_len:
    distribution: int_uniform
    max: 1024
    min: 256
  max_width:
    distribution: int_uniform
    max: 1344
    min: 336
  min_height:
    distribution: int_uniform
    max: 64
    min: 16
  min_width:
    distribution: int_uniform
    max: 64
    min: 16
  num_layers:
    distribution: int_uniform
    max: 16
    min: 2
  optimizer:
    distribution: categorical
    values:
      - Adam
      - SGD
      - Adadelta
      - RMSprop
      - Adamax
      - AdamW
      - Adagrad
      - SparseAdam
      - ASGD
      - LBFGS
      - NAdam
      - RAdam
      - Rprop
  patch_size:
    distribution: int_uniform
    max: 32
    min: 8
  scheduler:
    distribution: categorical
    values:
      - StepLR
      - LambdaLR
      - MultiplicativeLR
      - MultiStepLR
      - LinearLR
      - OneCycleLR
      - ConstantLR
      - ExponentialLR
      - CosineAnnealingLR
      - ChainedScheduler
      - SequentialLR
      - ReduceLROnPlateau
      - CyclicLR
      - CosineAnnealingWarmRestarts
  temperature:
    distribution: uniform
    max: 0.9
    min: 0.1
program: sweep.py
```
Is there any strange setting in this config? I will remove `gamma` and `optimizer`, `batchsize` and train more iterations.
